default_language_version:
  python: python3.13

repos:
  # Formatters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: [ --autofix, --no-sort-keys ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black

  # Linters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: debug-statements

  - repo: https://github.com/seddonym/import-linter
    rev: "v2.3"
    hooks:
      - id: import-linter

  - repo: https://github.com/python-poetry/poetry
    rev: '2.1.3'
    hooks:
      - id: poetry-check

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        require_serial: true
        language: system
        types: [ python ]
        args: ["--no-namespace-packages"]
