# mypy: ignore-errors
# ruff: noqa: INP001
"""User model.

Revision ID: 032adc3dc50f
Revises:
Create Date: 2025-08-30 23:26:44.092846

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "032adc3dc50f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("USER", "ADMIN", "MAIN_ADMIN", name="userrole").create(
        op.get_bind()
    )
    op.create_table(
        "users",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("tg_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "USER",
                "ADMIN",
                "MAIN_ADMIN",
                name="userrole",
                inherit_schema=True,
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
    )
    op.create_index(op.f("ix__users__tg_id"), "users", ["tg_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__users__tg_id"), table_name="users")
    op.drop_table("users")
    sa.Enum("USER", "ADMIN", "MAIN_ADMIN", name="userrole").drop(op.get_bind())
    # ### end Alembic commands ###
